permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://sedadogan.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: sedadogan
archive: Son Girdiler
assets: /assets
author: Seda Doğan
disqus: sedadogan
email: seda.dogan@bil.omu.edu.tr
feed: ~
flickr: ~
google: ~
googleanalyticsid: ~
googleplus: ~
gpg: ~
homeurl: http://sedadogan.github.com
logo: /assets/19/19-normal-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: sedadogan.github.com
ribbon: GitHub'dayım
title: Seda Doğan

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
